[package]
name = "clap_url"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4"
serde = "1.0"
serde_qs = "0.12"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
